Introducing new vector and matrix functions
Kapcash/ts-matrix pull request #4
Opened 2023-04-15 20:23 UTC by flbn

Was using this for some personal tinkering and ended up missing some functions that I think are fairly standard, mostly extending ESM `Array` functions:

Vector:
 - `.angleFrom()`
 - `.distanceFrom()`
 - `.indexOf()`
 - `._log()`
 - `.max()`
 - `.min()`
 - `.round()`
 
 Matrix:
 - `.indexOf()`
 - `._log()`
 - `.max()`
 - `.min()`
 - `.round()`
 
 Also, fixed some typos like `substract` is now `subtract`

2023-04-15 20:37 UTC, flbn commented
tests were added for all new methods. i have some more i was thinking of adding, but didn't know if i should fork and keep for my own needs.

things like:

Vector:
- `.dimension()` to get the real coordinate space
- `.rotate()` to rotate the coordinates. so, you'll need the angle to rotate and the axis as a param. if empty, could assume it's `(0,0)`

Matrix:
- `.dimension()` to get the rows and columns
- `.rank()` to get the rank of the matrix
- `.trace()` to get the trace of the matrix, should only work on a square matrix

2023-06-13 17:31 UTC, Kapcash requested changes
<img src="https://github.com/Kapcash/ts-matrix/assets/10612835/48e63f28-07a5-44db-a179-4147589387e4" height="150" />

I'm so **grateful** for your Pull Request! It's highly valuable and the code has great quality.
It's perfectly unit tested, what more can I ask for?

_Also, I'm sorry for the delay of reviewing this! I've never received any mail about this PR since I wasn't set as reviewer... I just saw it by accident yesterday haha_

Once merged, I'll upgrade the minor version of the library because it introduces a breaking change with the `subtract` typo.

Thanks you so much for taking the time to implement this!

2023-06-13 17:31 UTC, Kapcash commented on src/Matrix.ts
> +    }
For the record, I wanted to compare the performance of your implementation with another one: flattening the 2D array and use `findIndex`.
Results: the flatten implementation perf is similar with small matrices, but it's much more inefficient for big matrices.

```ts
    indexOfFlat(value: number): [number, number]  {
        const flatIndex = this.values.flat().findIndex(val => val === value);
        if (flatIndex < 0) {
            return [-1, -1];
        }

        const colIndex = flatIndex % this.columns;
        const rowIndex = (flatIndex - colIndex) / this.rows;
        return [rowIndex, colIndex];
    }
```

2023-06-13 17:31 UTC, Kapcash commented on src/Matrix.ts
> +    _log(): string {
What about overriding the `toString()` method directly?

2023-06-13 17:31 UTC, Kapcash commented on src/Vector.ts
> +    subtract(vector: Vector): Vector {
Hahaha, what a dummy typo! Thanks for fixing this :)

2023-06-13 17:31 UTC, Kapcash commented on src/Vector.ts
> +      _log = (): string => '[' + this.values.join(', ') + ']';
Same here, I'd just override `toString()`.
Also, it shouldn't be an arrow function but a class method!

2023-06-13 17:31 UTC, Kapcash commented on src/Vector.ts
> +     * Equivalent to |reciever - vector|
receiver* ;)

2023-07-11 08:51 UTC, Kapcash commented on yarn.lock
If you could revert the changes to this file, it would be great. I don't see any relevant changes, it just updated the targeted repo from yarn to npm (which in the end targets the same servers). It would avoid noises on the commits

2023-09-16 16:06 UTC, merged

2023-09-16 16:08 UTC, Kapcash commented
The library have been published to npm under the version 1.3.0.
Thank you so much again for your contribution!